#!/bin/bash

# Strip off the path info to find the name of this script
SCRIPT_NAME=`perl -e 'my $n = shift; $n =~ s#.+/##; print $n' $0`

# Use the refactored column adding code
MIG_DIR=`perl -MSocialtext::Migration -le 'print Socialtext::Migration::migration_script_dir'`
$MIG_DIR/add-column/$SCRIPT_NAME Workspace cascade_css boolean "'t'"

