#!/usr/bin/env perl

use strict;
use warnings;
use Socialtext::SQL qw(sql_singlevalue);

my $count = sql_singlevalue(q{
    SELECT COUNT(1) FROM attachment WHERE is_temporary = true});

if ($count > 0) {
    print "there are still temporary files in the `attachment` table\n";
    exit 1;
}

exit 0;
