#!/usr/bin/env perl
# @COPYRIGHT@
use strict;
use warnings;
use Socialtext::Migration::Utils qw/socialtext_schema_version/;
use Socialtext::SQL qw/sql_singlevalue/;

if ( socialtext_schema_version() < 59 ) {
    print "Adding 'lock' permissions and granting it to workspace admins.\n";
    exit 0;
}

my $permission_id = sql_singlevalue(qq{
 SELECT permission_id
   FROM "Permission"
  WHERE name = 'lock'
});

# if we don't have a lock perm, we need to do this migration.
unless ( $permission_id ) {
    print "Adding 'lock' permission and granting it to workspace admins.\n";
    exit 0;
}

my $ws_count = sql_singlevalue(qq{
 SELECT COUNT(*)
   FROM "Workspace"
});

my $role_id = sql_singlevalue(qq{
 SELECT role_id
   FROM "Role"
  WHERE name = 'workspace_admin'
});

my $locked_count = sql_singlevalue(qq{
 SELECT COUNT(*)
   FROM "WorkspaceRolePermission"
  WHERE role_id = ?
    AND permission_id = ?
}, $role_id, $permission_id);


if ( $locked_count == $ws_count ) {
    print "Workspace admins already have page locking permissions, skipping.\n";
    exit 1;
}

print "Adding 'lock' permissions and granting it to workspace admins.\n";
exit 0;
