#!/usr/bin/env perl
# @COPYRIGHT@
use strict;
use warnings;
use Socialtext::SQL qw/sql_singlevalue/;

my $has_account_user = eval { 
    sql_singlevalue(q{
        SELECT COUNT(*)
          FROM "Role"
         WHERE name = 'account_user'
    });
};

if (defined($has_account_user) && $has_account_user == 1) {
    print "Skipping migration 77: Account User Role already exists\n";
    exit 1;
}

print "Running migration 77: create Account User Role\n";
exit 0;
