AllSkins = [
    "s2 - Socialtext Classic Skin",
"abcwiki - ABC, it's as easy as 123",
"angel - Angel.com",
"angel2 - Angel.com",
"atsu - A.T. Still University",
"cex - Socialtext Customer Exchange",
"defragCon",
"drkw - Dresdner Kleinwort",
"dvp - DVP",
"dymo - Newell Rubbermaid",
"ebsworth - Ebsworth & Ebsworth",
"euriki - Euriki - Eurogroup Consulting Alliance",
"greenmountain - GreenMountain Engineering",
"humana - HUMANA",
"humanity - Humanity United",
"ideo - IDEO",
"infosys - CII Knowledge",
"law-wiki - Law Wiki",
"lp - Loan Performance",
"mosaic - Mosaic Knowledge Exchange",
"netapp - NetApp",
"netappacc - NetApp accenture",
"netappbp - NetApp BearingPoint",
"netapppqr - NetApp PQR (Partner Quarterly Roadshows)",
"netel - tel3.com",
"netsuite - NETSUITE Professional Services",
"newsgator - NewsGator",
"ogilvypr - 360º Digital Influence",
"omidyar - Omidyar Network",
"open - Socialtext OPEN",
"orrick - Orrick",
"pbwt - Patterson Belnap Webb & Taylor",
"pearson - Pearson",
"pinstripe - Pinstripe",
"referencemd - ReferenceMD - For Physicians by Physicians",
"rhio - RHIO",
"s2 - Socialtext Classic Skin",
"sap - SAP",
"symantec - Symantec",
"target - Target",
"tenacity - Tenacity Solutions Inc",
"unicef-education - Unicef Education",
"unicef-emergency - Unicef Emergency",
"uohio - Ohio Metaversity",
"vanilla - Proof of Concept REST API Skin",
"versalogic - VersaLogic Corporation",
"wapo - Washington Post",
"wikinomics - WIKINOMICS",
"wired - Wired Magazine"
];
