#!/usr/bin/env perl
# @COPYRIGHT@
use strict;
use warnings;
use Socialtext::Migration::Utils qw/ensure_socialtext_schema
                                    create_job_for_each_workspace
                                    create_job/;

# This job has been deleted
# create_job_for_each_workspace('IndexOffice2007PageAttachments');
create_job('IndexOffice2007SignalAttachments');

exit 0;
