#!/usr/bin/env perl

use strict;
use warnings;
use Socialtext::SQL qw/sql_singlevalue/;

my $count = sql_singlevalue(qq{
    SELECT COUNT(1)
      FROM attachment
     WHERE mime_type = ?
}, 'application/binary');

if ($count > 0) {
    exit 0;
}
else {
    print "no mime-type mismatches, skipping\n";
    exit 1;
}

