#!/usr/bin/env perl
# @COPYRIGHT@
use strict;
use warnings;
use Socialtext::AppConfig;
use Socialtext::File qw/get_contents/;

# This migration renames the db_schema_name field in socialtext.conf
# to a more accurate db_name field.

my $file = Socialtext::AppConfig->new->{file};
if (get_contents($file) =~ m/\bdb_schema_name: /) {
    print "db_schema_name field found - migration failed.\n";
    exit -1;
}

print "db_schema_name field not found - migration successful.\n";
exit 0;

