#!/bin/bash

DB=`st-config echo db_name`
DB_USER=`st-config echo db_user`

empty=`psql -U $DB_USER -d $DB -t -c '\d "Workspace"' | grep customjs_name`

if [ -z "$empty" ]; then
    echo "customjs_name column doesn't yet exist!"
    exit 0
fi

echo "customjs_name column already exists!"
exit 1
