#!/usr/bin/env perl
# @COPYRIGHT@

use strict;
use warnings;
use Socialtext::SQL qw/sql_singlevalue/;

my $containers = sql_singlevalue(qq{
  SELECT COUNT(*)
    FROM container
   WHERE container_type = ?
}, 'profile');

if ( $containers == 0 ) {
    print "No profile containers, skipping migration.\n";
    exit 1;
}

print "Resetting all user profiles.\n";
exit 0;
