#!/usr/bin/env perl
# @COPYRIGHT@
use strict;
use warnings;
use FindBin;
use lib "$FindBin::Bin/../lib";
use Socialtext::Resting::RegressionTest;
use Socialtext::File;

my $filename = shift or die "USAGE: $0 <tarball>\n";

my $rester = Socialtext::Resting::RegressionTest->new;

$rester->post_attachment(
    'Test Data', $filename, Socialtext::File::get_contents($filename),
    'application/x-gzip'
);
