#!/usr/bin/env perl
# @COPYRIGHT@
use strict;
use warnings;
use FindBin;
use lib "$FindBin::Bin/../lib";
use Cwd qw(cwd);
use Socialtext::MakeJS;
use Time::HiRes qw(time);

$Socialtext::MakeJS::VERBOSE = 1;

(my $base = $FindBin::Bin) =~ s{nlw/dev-bin$}{};
(my $dir = cwd) =~ s{^$base/nlw/share/}{};
$dir =~ s{^$base/plugins}{plugin};

my @targets = @ARGV ? @ARGV : ('all');
my $before = time;
for my $target (@targets) {
    if ($target eq 'all') {
        Socialtext::MakeJS->BuildAll;
    }
    elsif ($target eq 'cleanall') {
        Socialtext::MakeJS->CleanAll;;
    }
    elsif ($target eq 'clean') {
        Socialtext::MakeJS->CleanDir($dir);
    }
    elsif ($target eq 'loc') {
        system("$base/nlw/dev-bin/l10n-make-po-js");
    }
    else {
        Socialtext::MakeJS->Build($dir, $target);
    }
}
my $lapsed = (time - $before);
warn "Took $lapsed seconds.\n";
