#!/usr/bin/env perl
# @COPYRIGHT@
use strict;
use warnings;
use FindBin;
use lib "$FindBin::Bin/../lib";
use Cwd qw(cwd);
use Socialtext::JavaScript::Builder;
use Time::HiRes qw(time);

my $builder = Socialtext::JavaScript::Builder->new(
    verbose => 1,
);

(my $base = $FindBin::Bin) =~ s{nlw/dev-bin$}{};
(my $dir = cwd) =~ s{^$base/nlw/share/}{};
$dir =~ s{^$base/plugins}{plugin};

my @targets = @ARGV ? @ARGV : ('all');
my $before = time;
for my $target (@targets) {
    if ($target =~ /^clean(:?all)?$/) {
        $builder->clean();
    }
    elsif ($target eq 'loc') {
        system("$base/nlw/dev-bin/l10n-make-po-js");
    }
    elsif ($target eq 'all') {
        $builder->build();
    }
    else {
        $builder->build($target);
    }
}
my $lapsed = (time - $before);
warn "Took $lapsed seconds.\n";
