#!/usr/bin/env perl
# @COPYRIGHT@
use 5.12.0;
use autodie;
use warnings;
use open qw(:std :utf8);
use FindBin '$RealBin';
use lib "$RealBin/../lib";
use Socialtext::l10n::DevUtils;

chdir "$RealBin/..";
for my $po (glob("share/l10n/new/*.po")) {
    next unless -e $po and -s $po;
    my $en = $po;
    $en =~ s/\bnew\b/en/;

    system("perl -ni -e 'print unless /^# SOME DESCRIPTIVE TITLE./ .. /^#:/ and not /^#:/' $po");
    if (-e $en) {
        system("(msgcat --width 99999 -s $po $en > $en.new) && (mv $en.new $en)");
    }
    else {
        system("(msgcat --width 99999 -s $po > $en.new) && (mv $en.new $en)");
    }
    warn "*** Merged: $en\n";
}

system("dev-bin/l10n-make-po-js");
