#!/usr/bin/env perl
use 5.12.0;
use autodie;
use open qw(:std :utf8);
use Getopt::Long;
use FindBin '$RealBin';
use lib "$RealBin/../lib";
use Socialtext::l10n::DevUtils;

my ($in, $out);
for my $txt (@ARGV) {
    open $in, '<', $txt;
    my $out_file = $txt;
    $out_file =~ s/\.txt\b//;
    $out_file =~ s/\.po\b//;
    open $out, '>', "$out_file.po";
    select $out;

    local $/ = '[[[';
    scalar <$in>;
    print << ".";
# \@COPYRIGHT\@
msgid ""
msgstr ""
"Project-Id-Version: Socialtext i18n\\n"
"PO-Revision-Date: $po_revision_date\\n"
"Language-Team: Socialtext i18n team\\n"
"Last-Translator: Socialtext i18n team\\n"
"MIME-Version: 1.0\\n"
"Content-Type: text/plain; charset=UTF-8\\n"
"Content-Transfer-Encoding: 8bit\\n"

.
    while (<$in>) {
        s/\r//g;
        s/\n+$//;
        s/"/\\"/g;
        s/^/msgid "/;
        s!</>!\\n!;
        s/\]\]\]\s*/"\nmsgstr "/;
        s/\s*\[\[\[\s*/"\n\n/;
        print;
    }
    print qq["\n];

    close $in;
    close $out;
    select STDOUT;
    say "*** Converted: $out_file.po";
}
