#!/usr/bin/env perl
# @COPYRIGHT@
use strict;
use warnings;
use FindBin;
use lib "$FindBin::Bin/../lib";
use Socialtext::System qw/shell_run/;


# We must look at our path to determine the branch, as the `current` symlink
# is not used in testrunner.
(my $branch = $FindBin::Bin) =~ s#.+/([^/]+)/nlw/dev-bin$#$1#;

my $skin_link = "share/skin";
if (-d $skin_link) {
    print "Skin dir is a dir, not a link, so we'll leave it in place...\n";
    exit;
}
unlink $skin_link if -e $skin_link;

$branch = "branches/$branch" if $branch ne 'trunk';
my $skin_dir = "$FindBin::Bin/../../../socialtext-skins/$branch/skin";

# Look for a symlink to the repo beside nlw/
# set-branch and other tools set up this symlink
my $possible_skin_dir = "$FindBin::Bin/../../socialtext-skins/skin";
if (-d $possible_skin_dir) {
    $skin_dir = $possible_skin_dir;
}

# If no skin directory is available fall back to using the trunk, but complain
# about it so people know we didn't find a skin for this branch.
unless (-d $skin_dir) {
    warn "Skin dir ($skin_dir) not found! Using 'trunk' skin.\n";
    $skin_dir = "$FindBin::Bin/../../../socialtext-skins/trunk/skin";
}

die "Skin dir ($skin_dir) not found!" unless -d $skin_dir;
shell_run(qq{ln -sf $skin_dir $skin_link});

