#!/bin/bash

TMP="$HOME/st-make-js.log"

echo Making clean all in known directories
jsmake -clean all >& $TMP

echo Stopping ceq
nlwctl -c stop

echo Updating widgets
st-widgets update-all --verbose --force >> $TMP 2>&1

echo Updating widget gallery
st-widgets update-gallery --verbose --force >> $TMP 2>&1

echo Starting ceq
nlwctl -c start

echo logged to $TMP
